/* eslint-disable */
const metadata = {
    fields: {
        user: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            name: {
                name: 'name',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            email: {
                name: 'email',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            emailVerified: {
                name: 'emailVerified',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            image: {
                name: 'image',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            createdAt: {
                name: 'createdAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            updatedAt: {
                name: 'updatedAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            accounts: {
                name: 'accounts',
                type: 'Account',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            sessions: {
                name: 'sessions',
                type: 'Session',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            calendars: {
                name: 'calendars',
                type: 'Calendar',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
        },
        session: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            sessionToken: {
                name: 'sessionToken',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            userId: {
                name: 'userId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            expires: {
                name: 'expires',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            user: {
                name: 'user',
                type: 'User',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'sessions',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'userId' },
            },
        },
        account: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            userId: {
                name: 'userId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            type: {
                name: 'type',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            provider: {
                name: 'provider',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            providerAccountId: {
                name: 'providerAccountId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            refresh_token: {
                name: 'refresh_token',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            access_token: {
                name: 'access_token',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            expires_at: {
                name: 'expires_at',
                type: 'Int',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            token_type: {
                name: 'token_type',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            scope: {
                name: 'scope',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            id_token: {
                name: 'id_token',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            session_state: {
                name: 'session_state',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            user: {
                name: 'user',
                type: 'User',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'accounts',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'userId' },
            },
        },
        calendar: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            title: {
                name: 'title',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            description: {
                name: 'description',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            rows: {
                name: 'rows',
                type: 'Int',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            startDate: {
                name: 'startDate',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            visiiblity: {
                name: 'visiiblity',
                type: 'CalendarVisibility',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            userId: {
                name: 'userId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            user: {
                name: 'user',
                type: 'User',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'calendars',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'userId' },
            },
            events: {
                name: 'events',
                type: 'Event',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'calendar',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            timespans: {
                name: 'timespans',
                type: 'Timespan',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'calendar',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
        },
        event: {
            id: {
                name: 'id',
                type: 'Int',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            title: {
                name: 'title',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            date: {
                name: 'date',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            icon: {
                name: 'icon',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            calendarId: {
                name: 'calendarId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            calendar: {
                name: 'calendar',
                type: 'Calendar',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'events',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'calendarId' },
            },
        },
        timespan: {
            id: {
                name: 'id',
                type: 'Int',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            title: {
                name: 'title',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            startDate: {
                name: 'startDate',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            endDate: {
                name: 'endDate',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            color: {
                name: 'color',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            calendarId: {
                name: 'calendarId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            calendar: {
                name: 'calendar',
                type: 'Calendar',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'timespans',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'calendarId' },
            },
        },
    },
    uniqueConstraints: {
        user: {
            id: {
                name: 'id',
                fields: ['id'],
            },
            email: {
                name: 'email',
                fields: ['email'],
            },
        },
        session: {
            id: {
                name: 'id',
                fields: ['id'],
            },
            sessionToken: {
                name: 'sessionToken',
                fields: ['sessionToken'],
            },
        },
        account: {
            provider_providerAccountId: {
                name: 'provider_providerAccountId',
                fields: ['provider', 'providerAccountId'],
            },
            id: {
                name: 'id',
                fields: ['id'],
            },
        },
        calendar: {
            id: {
                name: 'id',
                fields: ['id'],
            },
        },
        event: {
            id: {
                name: 'id',
                fields: ['id'],
            },
        },
        timespan: {
            id: {
                name: 'id',
                fields: ['id'],
            },
        },
    },
    deleteCascade: {
        user: ['Session', 'Account', 'Calendar'],
        calendar: ['Event', 'Timespan'],
    },
    authModel: 'User',
};
export default metadata;
