import {
  IconAlertSquareRoundedFilled,
  IconArrowBigDownFilled,
  IconArrowBigUpFilled,
  IconAwardFilled,
  IconBellFilled,
  IconBookFilled,
  IconBulbFilled,
  IconCircleDotFilled,
  IconGiftFilled,
  IconHeartFilled,
  IconMessageCircle2Filled,
  IconSkull,
  IconStarFilled,
  IconTrophyFilled,
} from "@tabler/icons-react";

export const icons = {
  circle: IconCircleDotFilled,
  star: IconStarFilled,
  exclamation: IconAlertSquareRoundedFilled,
  skull: IconSkull,
  down: IconArrowBigDownFilled,
  up: IconArrowBigUpFilled,
  award: IconAwardFilled,
  bell: IconBellFilled,
  book: IconBookFilled,
  gift: IconGiftFilled,
  hear: IconHeartFilled,
  message: IconMessageCircle2Filled,
  trophy: IconTrophyFilled,
  bulb: IconBulbFilled,
};
